import { NextResponse } from 'next/server';

import { getBusinessDateValue } from '@/lib/business-date';
import {
    computePurchaseSummary,
    computePurchaseStatus,
    isInventoryUnit,
    isTireTrackedWarehouseItem,
    parseInventoryQuantity,
    parseWholeMoneyAmount,
} from '@/lib/inventory';
import { getSanityClient, sanityGetById } from '@/lib/sanity';
import { buildTireHistoryLogDoc, buildTireHistorySnapshot } from '@/lib/tire-history';
import { buildAutoGeneratedTireCode, buildTrackedTireStockMovementDoc } from '@/lib/tire-inventory';
import type {
    Purchase,
    PurchaseItem,
    PurchasePayment,
    StockMovement,
    StockMovementSourceType,
    TireEvent,
    Supplier,
    WarehouseItem,
} from '@/lib/types';

import {
    assertIsoDate,
    computeLedgerDebitBalance,
    getLedgerAccount,
    normalizeOptionalText,
    normalizeText,
    type ApiSession,
} from './data-helpers';

type AuditLogFn = (
    session: Pick<ApiSession, '_id' | 'name'>,
    action: string,
    entityType: string,
    entityRef: string,
    summary: string
) => void | Promise<void>;

type PurchaseCreateLine = {
    warehouseItemRef: string;
    orderedQty: number;
    unitPrice: number;
    notes?: string;
};

function formatAuditMoney(amount: number) {
    return `Rp ${Math.round(amount).toLocaleString('id-ID')}`;
}

function buildPurchaseNumber(dateValue: string, sequence: number) {
    const normalized = dateValue.replace(/-/g, '').slice(0, 6);
    return `PO-${normalized}-${String(sequence).padStart(4, '0')}`;
}

async function getNextPurchaseNumber(orderDate: string) {
    const period = orderDate.slice(0, 7).replace('-', '');
    const existing = await getSanityClient().fetch<Array<{ purchaseNumber?: string }>>(
        `*[_type == "purchase" && defined(orderDate) && orderDate match $periodPattern]{
            purchaseNumber
        }`,
        { periodPattern: `${orderDate.slice(0, 7)}*` }
    );
    const maxSequence = existing.reduce((max, row) => {
        const match = typeof row.purchaseNumber === 'string'
            ? row.purchaseNumber.match(/(\d{4})$/)
            : null;
        const parsed = match ? Number.parseInt(match[1], 10) : 0;
        return parsed > max ? parsed : max;
    }, 0);
    return buildPurchaseNumber(`${period.slice(0, 4)}-${period.slice(4, 6)}-01`, maxSequence + 1);
}

async function loadPurchaseBundle(purchaseId: string) {
    const [purchase, items, payments] = await Promise.all([
        sanityGetById<Purchase>(purchaseId),
        getSanityClient().fetch<PurchaseItem[]>(
            `*[_type == "purchaseItem" && purchaseRef == $ref] | order(_createdAt asc)`,
            { ref: purchaseId }
        ),
        getSanityClient().fetch<PurchasePayment[]>(
            `*[_type == "purchasePayment" && purchaseRef == $ref] | order(date asc, _createdAt asc)`,
            { ref: purchaseId }
        ),
    ]);
    if (!purchase || purchase._type !== 'purchase') {
        return null;
    }
    return { purchase, items, payments };
}

function buildPurchaseAuditSummary(purchaseNumber: string, supplierName: string, totalAmount: number) {
    return `Pembelian ${purchaseNumber} ke ${supplierName} sebesar ${formatAuditMoney(totalAmount)}`;
}

function buildPurchasePaymentAuditSummary(input: {
    purchaseNumber: string;
    supplierName: string;
    amount: number;
    bankName: string;
    note?: string;
}) {
    const base = `Bayar supplier ${formatAuditMoney(input.amount)} untuk ${input.purchaseNumber} (${input.supplierName}) via ${input.bankName}`;
    return input.note ? `${base} - ${input.note}` : base;
}

function buildStockMovementAuditSummary(input: {
    itemName: string;
    itemCode: string;
    quantity: number;
    sourceType: StockMovementSourceType;
    note?: string;
}) {
    const action = input.sourceType === 'MANUAL_OUT' ? 'Stok keluar' : 'Stok masuk';
    const base = `${action} ${input.itemCode} - ${input.itemName} sebanyak ${input.quantity}`;
    return input.note ? `${base} - ${input.note}` : base;
}

async function resolveSupplierSnapshot(supplierRef: string) {
    const supplier = await sanityGetById<Supplier>(supplierRef);
    if (!supplier || supplier._type !== 'supplier') {
        throw new Error('Supplier tidak ditemukan');
    }
    if (supplier.active === false) {
        throw new Error('Supplier tidak aktif');
    }
    return supplier;
}

async function resolveWarehouseItemSnapshot(itemRef: string, options?: { allowInactive?: boolean }) {
    const item = await sanityGetById<WarehouseItem>(itemRef);
    if (!item || item._type !== 'warehouseItem') {
        throw new Error('Barang gudang tidak ditemukan');
    }
    if (item.active === false && !options?.allowInactive) {
        throw new Error('Barang gudang tidak aktif');
    }
    if (!item.itemCode || !item.name || !item.unit || !isInventoryUnit(item.unit)) {
        throw new Error('Master barang gudang tidak valid');
    }
    return item;
}

function assertTrackedTireQuantity(quantity: number, label: string) {
    if (!Number.isInteger(quantity) || quantity <= 0) {
        throw new Error(`${label} harus berupa bilangan bulat lebih besar dari 0 untuk barang gudang ban tertracking`);
    }
}

function assertTrackedTireWarehouseItemDefaults(item: WarehouseItem) {
    if (!isTireTrackedWarehouseItem(item)) {
        return;
    }
    if (!item.tireBrandDefault?.trim() || !item.tireSizeDefault?.trim()) {
        throw new Error(`Master ${item.itemCode || item.name || item._id} belum punya merk dan ukuran ban default`);
    }
    if (item.tireTypeDefault !== 'Tubeless' && item.tireTypeDefault !== 'Tube Type' && item.tireTypeDefault !== 'Solid') {
        throw new Error(`Master ${item.itemCode || item.name || item._id} belum punya jenis ban default yang valid`);
    }
}

function normalizePurchaseLines(lines: unknown) {
    if (!Array.isArray(lines) || lines.length === 0) {
        throw new Error('Item pembelian wajib diisi');
    }

    const normalizedLines = lines.map((line, index) => {
        if (typeof line !== 'object' || line === null) {
            throw new Error(`Baris pembelian #${index + 1} tidak valid`);
        }
        const row = line as Record<string, unknown>;
        const warehouseItemRef = normalizeOptionalText(row.warehouseItemRef);
        const orderedQty = parseInventoryQuantity(row.orderedQty);
        const unitPrice = parseWholeMoneyAmount(row.unitPrice);
        const notes = normalizeOptionalText(row.notes);
        if (!warehouseItemRef) {
            throw new Error(`Barang pada baris pembelian #${index + 1} wajib dipilih`);
        }
        if (!Number.isFinite(orderedQty) || orderedQty <= 0) {
            throw new Error(`Qty pada baris pembelian #${index + 1} tidak valid`);
        }
        if (!Number.isFinite(unitPrice) || unitPrice < 0) {
            throw new Error(`Harga pada baris pembelian #${index + 1} tidak valid`);
        }
        return {
            warehouseItemRef,
            orderedQty,
            unitPrice,
            notes,
        } satisfies PurchaseCreateLine;
    });

    const uniqueItemRefs = new Set(normalizedLines.map(line => line.warehouseItemRef));
    if (uniqueItemRefs.size !== normalizedLines.length) {
        throw new Error('Barang pembelian tidak boleh duplikat dalam satu dokumen');
    }

    return normalizedLines;
}

export async function handlePurchaseCreate(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const supplierRef = normalizeOptionalText(data.supplierRef);
        const orderDate = normalizeOptionalText(data.orderDate) || getBusinessDateValue();
        const dueDate = normalizeOptionalText(data.dueDate);
        const notes = normalizeOptionalText(data.notes);
        const lines = normalizePurchaseLines(data.items);

        if (!supplierRef) {
            return NextResponse.json({ error: 'Supplier pembelian wajib dipilih' }, { status: 400 });
        }
        assertIsoDate(orderDate, 'Tanggal pembelian');
        if (dueDate) {
            assertIsoDate(dueDate, 'Jatuh tempo pembelian');
        }

        const supplier = await resolveSupplierSnapshot(supplierRef);
        const itemSnapshots = await Promise.all(lines.map(line => resolveWarehouseItemSnapshot(line.warehouseItemRef)));
        itemSnapshots.forEach((item, index) => {
            if (isTireTrackedWarehouseItem(item)) {
                assertTrackedTireWarehouseItemDefaults(item);
                assertTrackedTireQuantity(lines[index].orderedQty, `Qty pesan untuk ${item.itemCode || item.name || `baris #${index + 1}`}`);
            }
        });
        const purchaseNumber = await getNextPurchaseNumber(orderDate);
        const purchaseId = `purchase-${crypto.randomUUID()}`;

        const items = lines.map((line, index) => {
            const item = itemSnapshots[index];
            return {
                _id: `purchase-item-${crypto.randomUUID()}`,
                _type: 'purchaseItem',
                purchaseRef: purchaseId,
                warehouseItemRef: item._id,
                itemCode: item.itemCode,
                itemName: item.name,
                itemUnit: item.unit,
                trackingMode: item.trackingMode,
                tireTypeDefault: item.tireTypeDefault,
                tireBrandDefault: item.tireBrandDefault,
                tireSizeDefault: item.tireSizeDefault,
                orderedQty: line.orderedQty,
                receivedQty: 0,
                unitPrice: line.unitPrice,
                subtotal: Math.round(line.orderedQty * line.unitPrice),
                notes: line.notes,
            } satisfies PurchaseItem;
        });

        const summary = computePurchaseSummary({
            purchase: { status: 'ORDERED' },
            items,
            payments: [],
        });

        const purchaseDoc: Purchase = {
            _id: purchaseId,
            _type: 'purchase',
            purchaseNumber,
            supplierRef: supplier._id,
            supplierName: supplier.name,
            orderDate,
            dueDate: dueDate || undefined,
            status: 'ORDERED',
            notes,
            totalAmount: summary.totalAmount,
            totalOrderedQty: summary.totalOrderedQty,
            totalReceivedQty: 0,
            paidAmount: 0,
            outstandingAmount: summary.totalAmount,
            lineCount: items.length,
            createdBy: session._id,
            createdByName: session.name,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        };

        const transaction = getSanityClient().transaction().create(purchaseDoc);
        for (const item of items) {
            transaction.create(item);
        }
        await transaction.commit();

        await addAuditLog(
            session,
            'CREATE',
            'purchases',
            purchaseId,
            buildPurchaseAuditSummary(purchaseNumber, supplier.name, summary.totalAmount)
        );
        return NextResponse.json({ data: purchaseDoc, id: purchaseId });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Pembelian tidak valid' },
            { status: 400 }
        );
    }
}

export async function handlePurchaseReceive(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const purchaseRef = normalizeOptionalText(data.purchaseRef) || normalizeOptionalText(data.id);
        const receiveDate = normalizeOptionalText(data.receiveDate) || getBusinessDateValue();
        const receiptItems = Array.isArray(data.items) ? data.items : [];
        if (!purchaseRef) {
            return NextResponse.json({ error: 'Pembelian wajib dipilih' }, { status: 400 });
        }
        assertIsoDate(receiveDate, 'Tanggal terima barang');

        const bundle = await loadPurchaseBundle(purchaseRef);
        if (!bundle) {
            return NextResponse.json({ error: 'Pembelian tidak ditemukan' }, { status: 404 });
        }
        if (bundle.purchase.status === 'CANCELLED') {
            return NextResponse.json({ error: 'Pembelian yang dibatalkan tidak bisa menerima barang' }, { status: 409 });
        }

        const receiptMap = new Map<string, { receivedQty: number; note?: string }>();
        for (const [index, rawItem] of receiptItems.entries()) {
            if (typeof rawItem !== 'object' || rawItem === null) {
                return NextResponse.json({ error: `Baris penerimaan #${index + 1} tidak valid` }, { status: 400 });
            }
            const row = rawItem as Record<string, unknown>;
            const purchaseItemRef = normalizeOptionalText(row.purchaseItemRef);
            const receivedQty = parseInventoryQuantity(row.receivedQty);
            const note = normalizeOptionalText(row.note);
            if (!purchaseItemRef) {
                return NextResponse.json({ error: `Item pembelian pada baris penerimaan #${index + 1} tidak valid` }, { status: 400 });
            }
            if (!Number.isFinite(receivedQty) || receivedQty < 0) {
                return NextResponse.json({ error: `Qty terima pada baris #${index + 1} tidak valid` }, { status: 400 });
            }
            if (receivedQty > 0) {
                receiptMap.set(purchaseItemRef, { receivedQty, note });
            }
        }

        if (receiptMap.size === 0) {
            return NextResponse.json({ error: 'Isi minimal satu qty terima lebih besar dari 0' }, { status: 400 });
        }

        const transaction = getSanityClient().transaction();
        const nextItems: PurchaseItem[] = [];
        const movementDocs: StockMovement[] = [];
        const registeredTires: TireEvent[] = [];

        for (const [itemIndex, item] of bundle.items.entries()) {
            const receipt = receiptMap.get(item._id);
            if (!receipt) {
                nextItems.push(item);
                continue;
            }
            const remainingQty = Math.max(parseInventoryQuantity(item.orderedQty) - parseInventoryQuantity(item.receivedQty ?? 0), 0);
            if (receipt.receivedQty > remainingQty) {
                return NextResponse.json(
                    { error: `Qty terima untuk ${item.itemName || item.itemCode || item._id} melebihi sisa pesanan` },
                    { status: 409 }
                );
            }
            const warehouseItem = await resolveWarehouseItemSnapshot(item.warehouseItemRef, { allowInactive: true });
            if (isTireTrackedWarehouseItem(item) || isTireTrackedWarehouseItem(warehouseItem)) {
                assertTrackedTireWarehouseItemDefaults(warehouseItem);
                assertTrackedTireQuantity(
                    receipt.receivedQty,
                    `Qty terima untuk ${item.itemName || item.itemCode || item._id}`
                );
            }
            const currentStockQty = Math.max(parseInventoryQuantity(warehouseItem.currentStockQty ?? 0), 0);
            const nextStockQty = currentStockQty + receipt.receivedQty;
            const nextReceivedQty = Math.max(parseInventoryQuantity(item.receivedQty ?? 0), 0) + receipt.receivedQty;

            transaction.patch(item._id, patch => patch.set({ receivedQty: nextReceivedQty }));
            transaction.patch(warehouseItem._id, patch => patch.set({ currentStockQty: nextStockQty }));

            const movementDoc = buildTrackedTireStockMovementDoc({
                warehouseItem,
                quantity: receipt.receivedQty,
                balanceAfter: nextStockQty,
                movementDate: receiveDate,
                type: 'IN',
                sourceType: 'PURCHASE_RECEIPT',
                sourceRef: bundle.purchase._id,
                sourceNumber: bundle.purchase.purchaseNumber,
                note: receipt.note,
                createdBy: session._id,
                createdByName: session.name,
            });
            transaction.create(movementDoc);
            movementDocs.push(movementDoc);

            if (isTireTrackedWarehouseItem(item) || isTireTrackedWarehouseItem(warehouseItem)) {
                const batchStart = Math.max(parseInventoryQuantity(item.receivedQty ?? 0), 0);
                for (let sequence = 1; sequence <= receipt.receivedQty; sequence += 1) {
                    const nextSequence = batchStart + sequence;
                    const tireCode = buildAutoGeneratedTireCode({
                        purchaseNumber: bundle.purchase.purchaseNumber,
                        lineSequence: itemIndex + 1,
                        tireSequence: nextSequence,
                    });
                    const tireDoc: TireEvent = {
                        _id: `tire-event-${crypto.randomUUID()}`,
                        _type: 'tireEvent',
                        tireCode,
                        holderType: 'WAREHOUSE',
                        status: 'IN_WAREHOUSE',
                        posisi: 'Gudang Ban',
                        tireType: warehouseItem.tireTypeDefault || item.tireTypeDefault || 'Tubeless',
                        tireBrand: warehouseItem.tireBrandDefault || item.tireBrandDefault || item.itemName || warehouseItem.name,
                        tireSize: warehouseItem.tireSizeDefault || item.tireSizeDefault || '-',
                        linkedWarehouseItemRef: warehouseItem._id,
                        linkedWarehouseItemCode: warehouseItem.itemCode,
                        linkedWarehouseItemName: warehouseItem.name,
                        sourcePurchaseRef: bundle.purchase._id,
                        sourcePurchaseNumber: bundle.purchase.purchaseNumber,
                        sourcePurchaseItemRef: item._id,
                        sourceReceiveDate: receiveDate,
                        installDate: receiveDate,
                        notes: `Terdaftar otomatis dari pembelian ${bundle.purchase.purchaseNumber}`,
                    };
                    const historyLogDoc = buildTireHistoryLogDoc({
                        tireEventRef: tireDoc._id,
                        tireCode: tireDoc.tireCode,
                        tireBrand: tireDoc.tireBrand,
                        tireSize: tireDoc.tireSize,
                        previous: null,
                        next: buildTireHistorySnapshot(tireDoc),
                        session,
                        note: `Ban diterima dari pembelian ${bundle.purchase.purchaseNumber} dan masuk ke gudang ban`,
                    });
                    transaction.create(tireDoc);
                    transaction.create(historyLogDoc);
                    registeredTires.push(tireDoc);
                }
            }
            nextItems.push({ ...item, receivedQty: nextReceivedQty });
        }

        const summary = computePurchaseSummary({
            purchase: bundle.purchase,
            items: nextItems,
            payments: bundle.payments,
        });
        const nextStatus = computePurchaseStatus({
            totalOrderedQty: summary.totalOrderedQty,
            totalReceivedQty: summary.totalReceivedQty,
            totalAmount: summary.totalAmount,
            paidAmount: summary.paidAmount,
            existingStatus: bundle.purchase.status,
        });
        transaction.patch(bundle.purchase._id, patch => patch.set({
            totalReceivedQty: summary.totalReceivedQty,
            status: nextStatus,
            lastReceivedAt: receiveDate,
            updatedAt: new Date().toISOString(),
        }));
        await transaction.commit();

        await addAuditLog(
            session,
            'UPDATE',
            'purchases',
            bundle.purchase._id,
            `Terima barang untuk ${bundle.purchase.purchaseNumber} sebesar ${summary.totalReceivedQty}/${summary.totalOrderedQty}`
        );
        return NextResponse.json({
            success: true,
            data: {
                purchaseRef: bundle.purchase._id,
                stockMovements: movementDocs,
                registeredTires,
            },
        });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Penerimaan barang tidak valid' },
            { status: 400 }
        );
    }
}

export async function handleStockMovementCreate(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const warehouseItemRef = normalizeOptionalText(data.warehouseItemRef);
        const movementDate = normalizeOptionalText(data.movementDate) || getBusinessDateValue();
        const sourceType = normalizeText(data.sourceType).toUpperCase() as StockMovementSourceType;
        const quantity = parseInventoryQuantity(data.quantity);
        const note = normalizeOptionalText(data.note);

        if (!warehouseItemRef) {
            return NextResponse.json({ error: 'Barang gudang wajib dipilih' }, { status: 400 });
        }
        if (sourceType !== 'MANUAL_IN' && sourceType !== 'MANUAL_OUT') {
            return NextResponse.json({ error: 'Tipe mutasi stok manual tidak valid' }, { status: 400 });
        }
        assertIsoDate(movementDate, 'Tanggal mutasi stok');
        if (!Number.isFinite(quantity) || quantity <= 0) {
            return NextResponse.json({ error: 'Qty mutasi stok tidak valid' }, { status: 400 });
        }

        const warehouseItem = await resolveWarehouseItemSnapshot(warehouseItemRef);
        if (isTireTrackedWarehouseItem(warehouseItem)) {
            return NextResponse.json(
                { error: 'Mutasi stok manual untuk ban tertracking dikelola lewat modul Ban dan penerimaan pembelian' },
                { status: 409 }
            );
        }
        const currentStockQty = Math.max(parseInventoryQuantity(warehouseItem.currentStockQty ?? 0), 0);
        if (sourceType === 'MANUAL_OUT' && currentStockQty < quantity) {
            return NextResponse.json({ error: 'Stok barang tidak cukup untuk dikeluarkan' }, { status: 409 });
        }
        const nextStockQty = sourceType === 'MANUAL_OUT' ? currentStockQty - quantity : currentStockQty + quantity;

        const movementDoc: StockMovement = {
            _id: `stock-movement-${crypto.randomUUID()}`,
            _type: 'stockMovement',
            warehouseItemRef: warehouseItem._id,
            itemCode: warehouseItem.itemCode,
            itemName: warehouseItem.name,
            unit: warehouseItem.unit,
            movementDate,
            type: sourceType === 'MANUAL_OUT' ? 'OUT' : 'IN',
            sourceType,
            quantity,
            balanceAfter: nextStockQty,
            note,
            createdBy: session._id,
            createdByName: session.name,
        };

        await getSanityClient()
            .transaction()
            .patch(warehouseItem._id, patch => patch.set({ currentStockQty: nextStockQty }))
            .create(movementDoc)
            .commit();

        await addAuditLog(
            session,
            'CREATE',
            'stock-movements',
            movementDoc._id,
            buildStockMovementAuditSummary({
                itemName: warehouseItem.name,
                itemCode: warehouseItem.itemCode,
                quantity,
                sourceType,
                note,
            })
        );
        return NextResponse.json({ data: movementDoc, id: movementDoc._id });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Mutasi stok tidak valid' },
            { status: 400 }
        );
    }
}

export async function handlePurchasePaymentCreate(
    session: ApiSession,
    data: Record<string, unknown>,
    addAuditLog: AuditLogFn
) {
    try {
        const purchaseRef = normalizeOptionalText(data.purchaseRef);
        const bankAccountRef = normalizeOptionalText(data.bankAccountRef);
        const date = normalizeOptionalText(data.date) || getBusinessDateValue();
        const amount = parseWholeMoneyAmount(data.amount);
        const note = normalizeOptionalText(data.note);

        if (!purchaseRef) {
            return NextResponse.json({ error: 'Pembelian wajib dipilih' }, { status: 400 });
        }
        if (!bankAccountRef) {
            return NextResponse.json({ error: 'Rekening pembayaran supplier wajib dipilih' }, { status: 400 });
        }
        assertIsoDate(date, 'Tanggal pembayaran supplier');
        if (!Number.isFinite(amount) || amount <= 0) {
            return NextResponse.json({ error: 'Nominal pembayaran supplier tidak valid' }, { status: 400 });
        }

        const bundle = await loadPurchaseBundle(purchaseRef);
        if (!bundle) {
            return NextResponse.json({ error: 'Pembelian tidak ditemukan' }, { status: 404 });
        }
        if (bundle.purchase.status === 'CANCELLED') {
            return NextResponse.json({ error: 'Pembelian yang dibatalkan tidak bisa dibayar' }, { status: 409 });
        }

        const summary = computePurchaseSummary({
            purchase: bundle.purchase,
            items: bundle.items,
            payments: bundle.payments,
        });
        if (summary.outstandingAmount <= 0) {
            return NextResponse.json({ error: 'Pembelian ini sudah lunas' }, { status: 409 });
        }
        if (amount > summary.outstandingAmount) {
            return NextResponse.json({ error: 'Nominal bayar melebihi outstanding pembelian' }, { status: 409 });
        }

        const bankAccount = await getLedgerAccount(bankAccountRef);
        if (!bankAccount) {
            return NextResponse.json({ error: 'Rekening pembayaran supplier tidak ditemukan' }, { status: 404 });
        }
        const ledger = computeLedgerDebitBalance(bankAccount.currentBalance, amount);
        if (ledger.nextBalance < 0) {
            return NextResponse.json({ error: 'Saldo rekening tidak cukup untuk membayar supplier' }, { status: 409 });
        }

        const paymentId = `purchase-payment-${crypto.randomUUID()}`;
        const transactionId = `bank-transaction-${crypto.randomUUID()}`;
        const paymentDoc: PurchasePayment = {
            _id: paymentId,
            _type: 'purchasePayment',
            purchaseRef: bundle.purchase._id,
            purchaseNumber: bundle.purchase.purchaseNumber,
            supplierRef: bundle.purchase.supplierRef,
            supplierName: bundle.purchase.supplierName,
            date,
            amount,
            bankAccountRef: bankAccount._id,
            bankAccountName: bankAccount.bankName,
            bankAccountNumber: bankAccount.accountNumber,
            bankTransactionRef: transactionId,
            note,
            createdBy: session._id,
            createdByName: session.name,
        };
        const nextPayments = [...bundle.payments, paymentDoc];
        const nextSummary = computePurchaseSummary({
            purchase: bundle.purchase,
            items: bundle.items,
            payments: nextPayments,
        });
        const nextStatus = computePurchaseStatus({
            totalOrderedQty: nextSummary.totalOrderedQty,
            totalReceivedQty: nextSummary.totalReceivedQty,
            totalAmount: nextSummary.totalAmount,
            paidAmount: nextSummary.paidAmount,
            existingStatus: bundle.purchase.status,
        });

        await getSanityClient()
            .transaction()
            .create(paymentDoc)
            .create({
                _id: transactionId,
                _type: 'bankTransaction',
                bankAccountRef: bankAccount._id,
                bankAccountName: bankAccount.bankName,
                bankAccountNumber: bankAccount.accountNumber,
                type: 'DEBIT',
                amount,
                date,
                description: `Pembayaran supplier ${bundle.purchase.purchaseNumber} - ${bundle.purchase.supplierName || '-'}`,
                balanceAfter: ledger.nextBalance,
                relatedPurchasePaymentRef: paymentId,
                relatedPurchaseRef: bundle.purchase._id,
            })
            .patch(bankAccount._id, patch => patch.set({ currentBalance: ledger.nextBalance }))
            .patch(bundle.purchase._id, patch => patch.set({
                paidAmount: nextSummary.paidAmount,
                outstandingAmount: nextSummary.outstandingAmount,
                status: nextStatus,
                lastPaidAt: date,
                updatedAt: new Date().toISOString(),
            }))
            .commit();

        await addAuditLog(
            session,
            'CREATE',
            'purchase-payments',
            paymentId,
            buildPurchasePaymentAuditSummary({
                purchaseNumber: bundle.purchase.purchaseNumber,
                supplierName: bundle.purchase.supplierName || '-',
                amount,
                bankName: bankAccount.bankName,
                note,
            })
        );
        return NextResponse.json({ data: paymentDoc, id: paymentId });
    } catch (error) {
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Pembayaran supplier tidak valid' },
            { status: 400 }
        );
    }
}
