import {
  resolveTireAssetStatus,
  resolveTireHolderType,
  resolveTirePlacementLabel,
} from './tire-slots';
import type {
  StockMovement,
  TireEvent,
  WarehouseItem,
} from './types';

type TireLike = Pick<
  TireEvent,
  | 'tireCode'
  | 'holderType'
  | 'status'
  | 'linkedWarehouseItemRef'
  | 'linkedWarehouseItemCode'
  | 'linkedWarehouseItemName'
  | 'vehiclePlate'
  | 'externalPartyName'
  | 'externalPlateNumber'
  | 'slotCode'
  | 'posisi'
>;

export function countsTowardTrackedTireWarehouseStock(tire: Partial<TireLike> | Record<string, unknown>) {
  const hasPlacementSignal = Boolean(
    tire &&
    (
      'status' in tire ||
      'holderType' in tire ||
      'vehicleRef' in tire ||
      'vehiclePlate' in tire ||
      'externalPartyName' in tire ||
      'externalPlateNumber' in tire ||
      'linkedWarehouseItemRef' in tire ||
      'posisi' in tire
    )
  );
  if (!hasPlacementSignal) {
    return false;
  }
  const holderType = resolveTireHolderType(tire);
  const status = resolveTireAssetStatus(tire);
  return holderType === 'WAREHOUSE' && status === 'IN_WAREHOUSE';
}

export function buildAutoGeneratedTireCode(params: {
  purchaseNumber: string;
  lineSequence: number;
  tireSequence: number;
}) {
  const compactPurchaseNumber = params.purchaseNumber.replace(/[^A-Z0-9]/gi, '').toUpperCase() || 'PO';
  return `BAN-${compactPurchaseNumber}-${String(params.lineSequence).padStart(2, '0')}-${String(params.tireSequence).padStart(3, '0')}`;
}

export function buildTrackedTireStockMovementDoc(params: {
  warehouseItem: Pick<WarehouseItem, '_id' | 'itemCode' | 'name' | 'unit'>;
  quantity: number;
  balanceAfter: number;
  movementDate: string;
  type: StockMovement['type'];
  sourceType: StockMovement['sourceType'];
  sourceRef?: string;
  sourceNumber?: string;
  note?: string;
  createdBy?: string;
  createdByName?: string;
}) {
  return {
    _id: `stock-movement-${crypto.randomUUID()}`,
    _type: 'stockMovement',
    warehouseItemRef: params.warehouseItem._id,
    itemCode: params.warehouseItem.itemCode,
    itemName: params.warehouseItem.name,
    unit: params.warehouseItem.unit,
    movementDate: params.movementDate,
    type: params.type,
    sourceType: params.sourceType,
    sourceRef: params.sourceRef,
    sourceNumber: params.sourceNumber,
    quantity: params.quantity,
    balanceAfter: params.balanceAfter,
    note: params.note,
    createdBy: params.createdBy,
    createdByName: params.createdByName,
  } satisfies StockMovement;
}

export function buildTrackedTireWarehouseNote(params: {
  tireCode: string;
  fromPlacement?: string;
  toPlacement?: string;
}) {
  if (params.fromPlacement && params.toPlacement) {
    return `Ban ${params.tireCode} dipindahkan dari ${params.fromPlacement} ke ${params.toPlacement}`;
  }
  if (params.toPlacement) {
    return `Ban ${params.tireCode} masuk ke ${params.toPlacement}`;
  }
  if (params.fromPlacement) {
    return `Ban ${params.tireCode} keluar dari ${params.fromPlacement}`;
  }
  return `Mutasi ban ${params.tireCode}`;
}

export function resolveTrackedTirePlacementLabel(tire: Partial<TireLike> | Record<string, unknown>) {
  return resolveTirePlacementLabel(tire);
}
