/* ============================================================
   Gading Mas Surya - Sanity Seed Script
   Run: npm run seed:sanity
   ============================================================ */

import { createClient } from '@sanity/client';

import { loadScriptEnv, requireEnv } from './_env';

loadScriptEnv();

type SeedDoc = {
    _id: string;
    _type: string;
    [key: string]: unknown;
};

const client = createClient({
    projectId: requireEnv('NEXT_PUBLIC_SANITY_PROJECT_ID'),
    dataset: process.env.NEXT_PUBLIC_SANITY_DATASET?.trim() || 'production',
    apiVersion: process.env.SANITY_API_VERSION?.trim() || '2024-01-01',
    token: requireEnv('SANITY_API_TOKEN'),
    useCdn: false,
});

const OWNER_PASSWORD_HASH = '$2b$10$gmQQXBYsr6av5en3FKDsRuW/ZiOXB6hOqzD2EXmGWICdq2EADL2YW';
const ADMIN_PASSWORD_HASH = '$2b$10$RTJAvsAXXjPgBPdE/rXYqeQM6mn7lJG7qK8u/wML.qZZ2Bg7SB4Be';
const DRIVER_PASSWORD_HASH = '$2b$10$O9./WCIZQXNxhcLle.E9n.eJh35t9ej64F8sx9b2wKkCn93sTLmh.';

const documents: SeedDoc[] = [];

const bankAccounts = {
    'bank-jatim-001': {
        _id: 'bank-jatim-001',
        _type: 'bankAccount',
        bankName: 'Bank Jatim',
        accountNumber: '0201200300400',
        accountHolder: 'Gading Mas Surya',
        accountType: 'BANK',
        initialBalance: 150_000_000,
        currentBalance: 150_000_000,
        active: true,
        notes: 'Rekening penerimaan utama perusahaan',
    },
    'bank-bca-001': {
        _id: 'bank-bca-001',
        _type: 'bankAccount',
        bankName: 'BCA',
        accountNumber: '1234500012',
        accountHolder: 'Gading Mas Surya',
        accountType: 'BANK',
        initialBalance: 80_000_000,
        currentBalance: 80_000_000,
        active: true,
        notes: 'Rekening operasional dan vendor',
    },
    'bank-cash-on-hand': {
        _id: 'bank-cash-on-hand',
        _type: 'bankAccount',
        bankName: 'Kas Tunai',
        accountNumber: 'CASH',
        accountHolder: 'Gading Mas Surya',
        accountType: 'CASH',
        systemKey: 'cash-on-hand',
        initialBalance: 5_000_000,
        currentBalance: 5_000_000,
        active: true,
        notes: 'Kas tunai operasional untuk transaksi lapangan',
    },
} satisfies Record<string, SeedDoc & {
    currentBalance: number;
    initialBalance: number;
    bankName: string;
    accountNumber: string;
    accountHolder: string;
}>;

function push(...docs: SeedDoc[]) {
    documents.push(...docs);
}

function postBankTransaction(input: {
    _id: string;
    bankAccountRef: keyof typeof bankAccounts;
    type: 'CREDIT' | 'DEBIT' | 'TRANSFER_IN' | 'TRANSFER_OUT';
    amount: number;
    date: string;
    description: string;
    relatedPaymentRef?: string;
    relatedExpenseRef?: string;
    relatedTransferRef?: string;
    relatedVoucherRef?: string;
}) {
    const account = bankAccounts[input.bankAccountRef];
    const isCredit = input.type === 'CREDIT' || input.type === 'TRANSFER_IN';
    account.currentBalance += isCredit ? input.amount : -input.amount;

    push({
        _id: input._id,
        _type: 'bankTransaction',
        bankAccountRef: account._id,
        bankAccountName: account.bankName,
        bankAccountNumber: account.accountNumber,
        type: input.type,
        amount: input.amount,
        date: input.date,
        description: input.description,
        balanceAfter: account.currentBalance,
        relatedPaymentRef: input.relatedPaymentRef,
        relatedExpenseRef: input.relatedExpenseRef,
        relatedTransferRef: input.relatedTransferRef,
        relatedVoucherRef: input.relatedVoucherRef,
    });
}

function buildSeedDocuments() {
    push(
        {
            _id: 'user-owner-001',
            _type: 'user',
            name: 'Owner Utama',
            email: 'owner@company.local',
            role: 'OWNER',
            passwordHash: OWNER_PASSWORD_HASH,
            active: true,
            createdAt: '2026-03-01T08:00:00Z',
            lastLoginAt: '2026-03-16T11:30:00Z',
        },
        {
            _id: 'user-admin-001',
            _type: 'user',
            name: 'Admin Operasional',
            email: 'admin@company.local',
            role: 'ADMIN',
            passwordHash: ADMIN_PASSWORD_HASH,
            active: true,
            createdAt: '2026-03-01T08:15:00Z',
            lastLoginAt: '2026-03-16T11:05:00Z',
        },
        {
            _id: 'user-driver-001',
            _type: 'user',
            name: 'Driver Agus',
            email: 'driver.agus@company.local',
            role: 'DRIVER',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            passwordHash: DRIVER_PASSWORD_HASH,
            active: true,
            createdAt: '2026-03-01T08:30:00Z',
            lastLoginAt: '2026-03-16T09:40:00Z',
        },
        {
            _id: 'user-driver-002',
            _type: 'user',
            name: 'Driver Budi',
            email: 'driver.budi@company.local',
            role: 'DRIVER',
            driverRef: 'drv-002',
            driverName: 'Budi Hartono',
            passwordHash: DRIVER_PASSWORD_HASH,
            active: true,
            createdAt: '2026-03-01T08:35:00Z',
            lastLoginAt: '2026-03-16T09:42:00Z',
        },
        {
            _id: 'user-driver-003',
            _type: 'user',
            name: 'Driver Catur',
            email: 'driver.catur@company.local',
            role: 'DRIVER',
            driverRef: 'drv-003',
            driverName: 'Catur Wibowo',
            passwordHash: DRIVER_PASSWORD_HASH,
            active: true,
            createdAt: '2026-03-01T08:40:00Z',
            lastLoginAt: '2026-03-16T08:55:00Z',
        },
        {
            _id: 'company-001',
            _type: 'companyProfile',
            name: 'Gading Mas Surya',
            address: 'JL. KEMANTREN 08 - KEC. TULANGAN, KAB. SIDOARJO - JATIM - INDONESIA',
            phone: '(031) 8853000',
            email: 'gadingmassurya@gmail.com',
            bankName: 'Bank Jatim',
            bankAccount: '0201200300400',
            bankHolder: 'Gading Mas Surya',
            themeColor: '#0f766e',
            numberingSettings: {
                resiPrefix: 'R',
                resiCounter: 9,
                resiPeriod: '202603',
                doPrefix: 'DO',
                doCounter: 8,
                doPeriod: '202603',
                invoicePrefix: 'INV',
                invoiceCounter: 1,
                invoicePeriod: '202603',
                notaPrefix: 'NOTA',
                notaCounter: 3,
                notaPeriod: '202603',
                notaSeriesCode: '3',
                boronganPrefix: 'BRG',
                boronganCounter: 2,
                boronganPeriod: '202603',
                bonPrefix: 'BON',
                bonCounter: 2,
                bonPeriod: '202603',
                incidentPrefix: 'INC',
                incidentCounter: 4,
                incidentPeriod: '202603',
            },
            invoiceSettings: {
                defaultTermDays: 14,
                dueDateDays: 14,
                footerNote: 'Pembayaran hanya dilakukan ke rekening resmi perusahaan.',
                invoiceMode: 'ORDER',
            },
            documentSettings: {
                showContact: true,
                dateFormat: 'dd/MM/yyyy',
            },
        }
    );

    push(
        {
            _id: 'cust-001',
            _type: 'customer',
            name: 'PT Pangan Nusantara',
            address: 'Jl. Raya Industri Tulangan No. 18, Sidoarjo',
            contactPerson: 'Fitri Andayani',
            phone: '081234500001',
            email: 'fitri@pangannusantara.co.id',
            defaultPaymentTerm: 14,
            active: true,
        },
        {
            _id: 'cust-002',
            _type: 'customer',
            name: 'PT Baja Timur Abadi',
            address: 'Jl. KIG Raya Blok B12, Gresik',
            contactPerson: 'Yusuf Hamdani',
            phone: '081234500002',
            email: 'yusuf@bajatimur.co.id',
            defaultPaymentTerm: 30,
            active: true,
        },
        {
            _id: 'cust-003',
            _type: 'customer',
            name: 'CV Sembada Plastik',
            address: 'Jl. Rungkut Industri II No. 7, Surabaya',
            contactPerson: 'Maya Wulansari',
            phone: '081234500003',
            email: 'maya@sembadaplastik.co.id',
            defaultPaymentTerm: 21,
            active: true,
        },
        {
            _id: 'cust-004',
            _type: 'customer',
            name: 'PT Arsip Lama',
            address: 'Jl. Veteran No. 44, Surabaya',
            contactPerson: 'Arif Hidayat',
            phone: '081234500004',
            email: 'arsip@contoh.co.id',
            defaultPaymentTerm: 14,
            active: false,
        },
        {
            _id: 'svc-001',
            _type: 'service',
            name: 'Reguler',
            description: 'Pengiriman reguler antarkota untuk muatan umum.',
            active: true,
        },
        {
            _id: 'svc-002',
            _type: 'service',
            name: 'Express',
            description: 'Pengiriman prioritas dengan SLA lebih cepat.',
            active: true,
        },
        {
            _id: 'svc-003',
            _type: 'service',
            name: 'FTL',
            description: 'Full truck load untuk muatan partai besar.',
            active: true,
        },
        {
            _id: 'svc-004',
            _type: 'service',
            name: 'Layanan Lama',
            description: 'Layanan lama yang sudah tidak dipakai.',
            active: false,
        },
        { _id: 'expcat-001', _type: 'expenseCategory', name: 'BBM / Solar', active: true },
        { _id: 'expcat-002', _type: 'expenseCategory', name: 'Tol & Parkir', active: true },
        { _id: 'expcat-003', _type: 'expenseCategory', name: 'Servis Kendaraan', active: true },
        { _id: 'expcat-004', _type: 'expenseCategory', name: 'Operasional Kantor', active: true },
        { _id: 'expcat-005', _type: 'expenseCategory', name: 'Konsumsi Driver', active: true },
        { _id: 'expcat-006', _type: 'expenseCategory', name: 'Borongan Supir', active: true },
        { _id: 'expcat-007', _type: 'expenseCategory', name: 'Lain-lain', active: true },
        { _id: 'expcat-008', _type: 'expenseCategory', name: 'Kategori Lama', active: false },
    );

    push(
        {
            _id: 'drv-001',
            _type: 'driver',
            name: 'Agus Santoso',
            phone: '081298760001',
            licenseNumber: 'SIM-B2-AGUS-001',
            ktpNumber: '3515010101010001',
            simExpiry: '2028-06-30',
            address: 'Tulangan, Sidoarjo',
            active: true,
            activeTrackingDeliveryOrderRef: 'do-003',
            activeTrackingUpdatedAt: '2026-03-16T09:38:00Z',
        },
        {
            _id: 'drv-002',
            _type: 'driver',
            name: 'Budi Hartono',
            phone: '081298760002',
            licenseNumber: 'SIM-B2-BUDI-002',
            ktpNumber: '3515010101010002',
            simExpiry: '2027-11-30',
            address: 'Waru, Sidoarjo',
            active: true,
            activeTrackingDeliveryOrderRef: 'do-004',
            activeTrackingUpdatedAt: '2026-03-16T09:41:00Z',
        },
        {
            _id: 'drv-003',
            _type: 'driver',
            name: 'Catur Wibowo',
            phone: '081298760003',
            licenseNumber: 'SIM-B2-CATUR-003',
            ktpNumber: '3515010101010003',
            simExpiry: '2028-01-15',
            address: 'Kediri Kota',
            active: true,
            activeTrackingDeliveryOrderRef: 'do-008',
            activeTrackingUpdatedAt: '2026-03-16T08:58:00Z',
        },
        {
            _id: 'drv-004',
            _type: 'driver',
            name: 'Deni Prabowo',
            phone: '081298760004',
            licenseNumber: 'SIM-B2-DENI-004',
            ktpNumber: '3515010101010004',
            simExpiry: '2026-10-01',
            address: 'Mojokerto',
            active: false,
        },
        {
            _id: 'veh-001',
            _type: 'vehicle',
            unitCode: 'GM-001',
            plateNumber: 'W 8123 GS',
            vehicleType: 'TRUCK',
            brandModel: 'Mitsubishi Colt Diesel FE 74',
            year: 2022,
            capacityKg: 4000,
            capacityVolume: 18,
            chassisNumber: 'MTSFE740001',
            engineNumber: 'ENGFE740001',
            status: 'ACTIVE',
            base: 'Sidoarjo',
            notes: 'Armada reguler area Surabaya - Sidoarjo',
            lastOdometer: 84500,
            lastOdometerAt: '2026-03-12',
        },
        {
            _id: 'veh-002',
            _type: 'vehicle',
            unitCode: 'GM-002',
            plateNumber: 'L 9456 AB',
            vehicleType: 'TRUCK',
            brandModel: 'Hino Dutro 110 SDL',
            year: 2021,
            capacityKg: 5000,
            capacityVolume: 22,
            chassisNumber: 'HNODUTRO002',
            engineNumber: 'ENGDUTRO002',
            status: 'IN_SERVICE',
            base: 'Gresik',
            notes: 'Armada heavy-duty untuk FTL dan pabrik',
            lastOdometer: 120300,
            lastOdometerAt: '2026-03-04',
        },
        {
            _id: 'veh-003',
            _type: 'vehicle',
            unitCode: 'GM-003',
            plateNumber: 'N 7788 CD',
            vehicleType: 'TRUCK',
            brandModel: 'Isuzu Elf NMR 71',
            year: 2019,
            capacityKg: 3500,
            capacityVolume: 16,
            chassisNumber: 'ISUZUNMR003',
            engineNumber: 'ENGNMR003',
            status: 'OUT_OF_SERVICE',
            base: 'Malang',
            notes: 'Menunggu keputusan overhaul mesin',
            lastOdometer: 167200,
            lastOdometerAt: '2026-02-28',
        },
        {
            _id: 'veh-004',
            _type: 'vehicle',
            unitCode: 'GM-004',
            plateNumber: 'W 1122 EF',
            vehicleType: 'TRUCK',
            brandModel: 'Toyota Dyna 130 HT',
            year: 2017,
            capacityKg: 3000,
            capacityVolume: 14,
            chassisNumber: 'TOYDYNA004',
            engineNumber: 'ENGDYNA004',
            status: 'SOLD',
            base: 'Sidoarjo',
            notes: 'Unit lama sudah dijual pada awal 2026',
            lastOdometer: 188420,
            lastOdometerAt: '2026-01-10',
        },
        {
            _id: 'veh-005',
            _type: 'vehicle',
            unitCode: 'GM-005',
            plateNumber: 'AG 3344 HI',
            vehicleType: 'TRUCK',
            brandModel: 'Mitsubishi Canter HDX',
            year: 2023,
            capacityKg: 4500,
            capacityVolume: 20,
            chassisNumber: 'MTSHDX005',
            engineNumber: 'ENGHDX005',
            status: 'ACTIVE',
            base: 'Kediri',
            notes: 'Armada backup untuk rute Kediri - Jombang',
            lastOdometer: 58210,
            lastOdometerAt: '2026-03-15',
        }
    );

    push(
        {
            _id: 'order-001',
            _type: 'order',
            masterResi: 'R-202603-0001',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            receiverName: 'Samsul Hadi',
            receiverPhone: '081777100001',
            receiverAddress: 'Jl. Margomulyo No. 88, Surabaya',
            receiverCompany: 'PT Retail Sentosa Surabaya',
            pickupAddress: 'Gudang Gading Mas Surya - Tulangan',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            status: 'COMPLETE',
            notes: 'Order reguler untuk distribusi retail Surabaya.',
            createdAt: '2026-03-02T08:00:00Z',
            createdBy: 'user-owner-001',
        },
        {
            _id: 'order-002',
            _type: 'order',
            masterResi: 'R-202603-0002',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            receiverName: 'Rizal Firmansyah',
            receiverPhone: '081777100002',
            receiverAddress: 'Jl. KIG Raya Blok C2, Gresik',
            receiverCompany: 'PT Baja Timur Abadi Plant 2',
            pickupAddress: 'Pabrik Baja Timur - Gresik',
            serviceRef: 'svc-003',
            serviceName: 'FTL',
            status: 'PARTIAL',
            notes: 'Batch pertama sudah jalan, batch kedua menunggu release gudang.',
            createdAt: '2026-03-03T09:00:00Z',
            createdBy: 'user-admin-001',
        },
        {
            _id: 'order-003',
            _type: 'order',
            masterResi: 'R-202603-0003',
            customerRef: 'cust-003',
            customerName: 'CV Sembada Plastik',
            receiverName: 'Taufik Akbar',
            receiverPhone: '081777100003',
            receiverAddress: 'Jl. By Pass Mojokerto No. 12, Mojokerto',
            receiverCompany: 'CV Sembada Plastik Cabang Mojokerto',
            pickupAddress: 'Gudang Rungkut Industri II No. 7, Surabaya',
            serviceRef: 'svc-002',
            serviceName: 'Express',
            status: 'PARTIAL',
            notes: 'Satu armada sedang dalam perjalanan, sisa dokumen belum ikut.',
            createdAt: '2026-03-10T07:45:00Z',
            createdBy: 'user-admin-001',
        },
        {
            _id: 'order-004',
            _type: 'order',
            masterResi: 'R-202603-0004',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            receiverName: 'Lina Marlina',
            receiverPhone: '081777100004',
            receiverAddress: 'Jl. Raya Bangil No. 14, Pasuruan',
            receiverCompany: 'Distribusi Pangan Pasuruan',
            pickupAddress: 'Gudang Gading Mas Surya - Tulangan',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            status: 'PARTIAL',
            notes: 'Armada sudah tiba di lokasi, menunggu unload dan POD.',
            createdAt: '2026-03-11T10:00:00Z',
            createdBy: 'user-owner-001',
        },
        {
            _id: 'order-005',
            _type: 'order',
            masterResi: 'R-202603-0005',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            receiverName: 'Arman Setiawan',
            receiverPhone: '081777100005',
            receiverAddress: 'Jl. Raya Jombang No. 9, Jombang',
            receiverCompany: 'Workshop Jombang Steel',
            pickupAddress: 'Pabrik Baja Timur - Gresik',
            serviceRef: 'svc-002',
            serviceName: 'Express',
            status: 'OPEN',
            notes: 'Surat jalan sudah dibuat, kendaraan dijadwalkan berangkat besok.',
            createdAt: '2026-03-12T13:10:00Z',
            createdBy: 'user-admin-001',
        },
        {
            _id: 'order-006',
            _type: 'order',
            masterResi: 'R-202603-0006',
            customerRef: 'cust-003',
            customerName: 'CV Sembada Plastik',
            receiverName: 'Anisa Putri',
            receiverPhone: '081777100006',
            receiverAddress: 'Jl. Ahmad Yani No. 31, Sidoarjo',
            receiverCompany: 'CV Sembada Plastik Gudang Sidoarjo',
            pickupAddress: 'Gudang Rungkut Industri II No. 7, Surabaya',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            status: 'ON_HOLD',
            notes: 'Barang ditahan sampai dokumen legalisasi lengkap.',
            createdAt: '2026-03-12T15:25:00Z',
            createdBy: 'user-admin-001',
        },
        {
            _id: 'order-007',
            _type: 'order',
            masterResi: 'R-202603-0007',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            receiverName: 'Fajar Nugroho',
            receiverPhone: '081777100007',
            receiverAddress: 'Jl. Mastrip No. 77, Kediri',
            receiverCompany: 'Pusat Distribusi Kediri',
            pickupAddress: 'Gudang Gading Mas Surya - Tulangan',
            serviceRef: 'svc-003',
            serviceName: 'FTL',
            status: 'CANCELLED',
            notes: 'Order dibatalkan customer sebelum armada berangkat.',
            createdAt: '2026-03-13T09:20:00Z',
            createdBy: 'user-owner-001',
        },
        {
            _id: 'order-008',
            _type: 'order',
            masterResi: 'R-202603-0008',
            customerRef: 'cust-003',
            customerName: 'CV Sembada Plastik',
            receiverName: 'Dewi Kurniasih',
            receiverPhone: '081777100008',
            receiverAddress: 'Jl. Veteran No. 5, Kediri',
            receiverCompany: 'PT Recycle Kediri',
            pickupAddress: 'Gudang Rungkut Industri II No. 7, Surabaya',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            status: 'COMPLETE',
            notes: 'Pengiriman selesai dan sudah masuk nota outstanding.',
            createdAt: '2026-03-04T11:15:00Z',
            createdBy: 'user-admin-001',
        },
        {
            _id: 'order-009',
            _type: 'order',
            masterResi: 'R-202603-0009',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            receiverName: 'Hendra Wijaya',
            receiverPhone: '081777100009',
            receiverAddress: 'Jl. Ahmad Dahlan No. 2, Kediri',
            receiverCompany: 'Baja Timur Kediri',
            pickupAddress: 'Pabrik Baja Timur - Gresik',
            serviceRef: 'svc-002',
            serviceName: 'Express',
            status: 'OPEN',
            notes: 'Armada sudah bergerak ke titik pickup.',
            createdAt: '2026-03-15T07:10:00Z',
            createdBy: 'user-admin-001',
        },
    );

    push(
        { _id: 'oi-001', _type: 'orderItem', orderRef: 'order-001', description: 'Beras premium 25 kg', qtyKoli: 4, weight: 80, volume: 0.4, value: 7_200_000, status: 'DELIVERED' },
        { _id: 'oi-002', _type: 'orderItem', orderRef: 'order-001', description: 'Minyak goreng kemasan', qtyKoli: 6, weight: 120, volume: 0.6, value: 9_000_000, status: 'DELIVERED' },
        { _id: 'oi-003', _type: 'orderItem', orderRef: 'order-002', description: 'Plat baja ringan', qtyKoli: 8, weight: 240, volume: 1.2, value: 16_500_000, status: 'DELIVERED' },
        { _id: 'oi-004', _type: 'orderItem', orderRef: 'order-002', description: 'Baut dan aksesoris pemasangan', qtyKoli: 4, weight: 60, volume: 0.3, value: 1_200_000, status: 'PENDING' },
        { _id: 'oi-005', _type: 'orderItem', orderRef: 'order-003', description: 'Resin batch A', qtyKoli: 5, weight: 150, volume: 0.8, value: 12_000_000, status: 'ON_DELIVERY' },
        { _id: 'oi-006', _type: 'orderItem', orderRef: 'order-003', description: 'Dokumen QC dan sertifikat', qtyKoli: 1, weight: 5, volume: 0.03, value: 150_000, status: 'PENDING' },
        { _id: 'oi-007', _type: 'orderItem', orderRef: 'order-004', description: 'Bahan kemasan produksi', qtyKoli: 7, weight: 210, volume: 1, value: 8_750_000, status: 'ON_DELIVERY' },
        { _id: 'oi-008', _type: 'orderItem', orderRef: 'order-004', description: 'Pallet kayu', qtyKoli: 2, weight: 40, volume: 0.2, value: 600_000, status: 'PENDING' },
        { _id: 'oi-009', _type: 'orderItem', orderRef: 'order-005', description: 'Sparepart conveyor', qtyKoli: 3, weight: 75, volume: 0.35, value: 4_500_000, status: 'PENDING' },
        { _id: 'oi-010', _type: 'orderItem', orderRef: 'order-006', description: 'Dokumen legalisasi ekspor', qtyKoli: 1, weight: 2, volume: 0.01, value: 300_000, status: 'HOLD' },
        { _id: 'oi-011', _type: 'orderItem', orderRef: 'order-007', description: 'Mesin packing', qtyKoli: 2, weight: 180, volume: 0.9, value: 18_000_000, status: 'PENDING' },
        { _id: 'oi-012', _type: 'orderItem', orderRef: 'order-008', description: 'Biji plastik recycle', qtyKoli: 6, weight: 180, volume: 0.9, value: 6_500_000, status: 'DELIVERED' },
        { _id: 'oi-013', _type: 'orderItem', orderRef: 'order-009', description: 'Plat potong custom', qtyKoli: 5, weight: 140, volume: 0.7, value: 9_800_000, status: 'PENDING' },
    );

    push(
        {
            _id: 'do-001',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0001',
            orderRef: 'order-001',
            masterResi: 'R-202603-0001',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            receiverName: 'Samsul Hadi',
            receiverPhone: '081777100001',
            receiverAddress: 'Jl. Margomulyo No. 88, Surabaya',
            receiverCompany: 'PT Retail Sentosa Surabaya',
            pickupAddress: 'Gudang Gading Mas Surya - Tulangan',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            date: '2026-03-03',
            status: 'DELIVERED',
            notes: 'Pengiriman reguler selesai di hari yang sama.',
            podReceiverName: 'Samsul Hadi',
            podReceivedDate: '2026-03-03',
            podNote: 'Barang diterima lengkap dan kondisi baik.',
            taripBorongan: 1_350_000,
            keteranganBorongan: 'Borongan trip reguler Surabaya kota.',
            trackingState: 'STOPPED',
            trackingStartedAt: '2026-03-03T01:20:00Z',
            trackingStoppedAt: '2026-03-03T10:30:00Z',
            trackingLastSeenAt: '2026-03-03T10:28:00Z',
            trackingLastLat: -7.2575,
            trackingLastLng: 112.7521,
            trackingLastAccuracyM: 9,
            trackingLastSpeedKph: 0,
            trackingLastSource: 'DRIVER_APP',
        },
        {
            _id: 'do-002',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0002',
            orderRef: 'order-002',
            masterResi: 'R-202603-0002',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            vehicleRef: 'veh-002',
            vehiclePlate: 'L 9456 AB',
            driverRef: 'drv-002',
            driverName: 'Budi Hartono',
            receiverName: 'Rizal Firmansyah',
            receiverPhone: '081777100002',
            receiverAddress: 'Jl. KIG Raya Blok C2, Gresik',
            receiverCompany: 'PT Baja Timur Abadi Plant 2',
            pickupAddress: 'Pabrik Baja Timur - Gresik',
            serviceRef: 'svc-003',
            serviceName: 'FTL',
            date: '2026-03-04',
            status: 'DELIVERED',
            notes: 'Batch pertama baja selesai dikirim.',
            podReceiverName: 'Rizal Firmansyah',
            podReceivedDate: '2026-03-04',
            podNote: 'Diterima oleh plant supervisor.',
            taripBorongan: 672_000,
            keteranganBorongan: 'Borongan trip FTL pabrik area Gresik.',
            trackingState: 'STOPPED',
            trackingStartedAt: '2026-03-04T00:50:00Z',
            trackingStoppedAt: '2026-03-04T08:45:00Z',
            trackingLastSeenAt: '2026-03-04T08:44:00Z',
            trackingLastLat: -7.1543,
            trackingLastLng: 112.6561,
            trackingLastAccuracyM: 12,
            trackingLastSpeedKph: 0,
            trackingLastSource: 'DRIVER_APP',
        },
        {
            _id: 'do-003',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0003',
            orderRef: 'order-003',
            masterResi: 'R-202603-0003',
            customerRef: 'cust-003',
            customerName: 'CV Sembada Plastik',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            receiverName: 'Taufik Akbar',
            receiverPhone: '081777100003',
            receiverAddress: 'Jl. By Pass Mojokerto No. 12, Mojokerto',
            receiverCompany: 'CV Sembada Plastik Cabang Mojokerto',
            pickupAddress: 'Gudang Rungkut Industri II No. 7, Surabaya',
            serviceRef: 'svc-002',
            serviceName: 'Express',
            date: '2026-03-14',
            status: 'ON_DELIVERY',
            notes: 'Armada sedang menuju tujuan akhir.',
            taripBorongan: 480_000,
            keteranganBorongan: 'Borongan trip express Surabaya - Mojokerto.',
            trackingState: 'ACTIVE',
            trackingStartedAt: '2026-03-14T01:10:00Z',
            trackingLastSeenAt: '2026-03-16T09:37:00Z',
            trackingLastLat: -7.4706,
            trackingLastLng: 112.4358,
            trackingLastAccuracyM: 7,
            trackingLastSpeedKph: 42,
            trackingLastSource: 'DRIVER_APP',
        },
        {
            _id: 'do-004',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0004',
            orderRef: 'order-004',
            masterResi: 'R-202603-0004',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            vehicleRef: 'veh-002',
            vehiclePlate: 'L 9456 AB',
            driverRef: 'drv-002',
            driverName: 'Budi Hartono',
            receiverName: 'Lina Marlina',
            receiverPhone: '081777100004',
            receiverAddress: 'Jl. Raya Bangil No. 14, Pasuruan',
            receiverCompany: 'Distribusi Pangan Pasuruan',
            pickupAddress: 'Gudang Gading Mas Surya - Tulangan',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            date: '2026-03-15',
            status: 'ARRIVED',
            notes: 'Armada sudah tiba, menunggu proses bongkar dan tanda terima.',
            taripBorongan: 630_000,
            keteranganBorongan: 'Borongan trip reguler Sidoarjo - Pasuruan.',
            trackingState: 'ACTIVE',
            trackingStartedAt: '2026-03-15T02:00:00Z',
            trackingLastSeenAt: '2026-03-16T09:40:00Z',
            trackingLastLat: -7.6451,
            trackingLastLng: 112.9077,
            trackingLastAccuracyM: 10,
            trackingLastSpeedKph: 0,
            trackingLastSource: 'DRIVER_APP',
        },
        {
            _id: 'do-005',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0005',
            orderRef: 'order-005',
            masterResi: 'R-202603-0005',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            vehicleRef: 'veh-005',
            vehiclePlate: 'AG 3344 HI',
            driverRef: 'drv-003',
            driverName: 'Catur Wibowo',
            receiverName: 'Arman Setiawan',
            receiverPhone: '081777100005',
            receiverAddress: 'Jl. Raya Jombang No. 9, Jombang',
            receiverCompany: 'Workshop Jombang Steel',
            pickupAddress: 'Pabrik Baja Timur - Gresik',
            serviceRef: 'svc-002',
            serviceName: 'Express',
            date: '2026-03-18',
            status: 'CREATED',
            notes: 'DO sudah dijadwalkan untuk keberangkatan besok pagi.',
            trackingState: 'IDLE',
        },
        {
            _id: 'do-006',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0006',
            orderRef: 'order-008',
            masterResi: 'R-202603-0008',
            customerRef: 'cust-003',
            customerName: 'CV Sembada Plastik',
            vehicleRef: 'veh-005',
            vehiclePlate: 'AG 3344 HI',
            driverRef: 'drv-003',
            driverName: 'Catur Wibowo',
            receiverName: 'Dewi Kurniasih',
            receiverPhone: '081777100008',
            receiverAddress: 'Jl. Veteran No. 5, Kediri',
            receiverCompany: 'PT Recycle Kediri',
            pickupAddress: 'Gudang Rungkut Industri II No. 7, Surabaya',
            serviceRef: 'svc-001',
            serviceName: 'Reguler',
            date: '2026-03-05',
            status: 'DELIVERED',
            notes: 'Pengiriman selesai dan siap ditagihkan.',
            podReceiverName: 'Dewi Kurniasih',
            podReceivedDate: '2026-03-05',
            podNote: 'Muatan lengkap diterima gudang Kediri.',
            taripBorongan: 738_000,
            keteranganBorongan: 'Borongan trip reguler Surabaya - Kediri.',
            trackingState: 'STOPPED',
            trackingStartedAt: '2026-03-05T00:45:00Z',
            trackingStoppedAt: '2026-03-05T08:30:00Z',
            trackingLastSeenAt: '2026-03-05T08:28:00Z',
            trackingLastLat: -7.8163,
            trackingLastLng: 112.0113,
            trackingLastAccuracyM: 8,
            trackingLastSpeedKph: 0,
            trackingLastSource: 'DRIVER_APP',
        },
        {
            _id: 'do-007',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0007',
            orderRef: 'order-007',
            masterResi: 'R-202603-0007',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            vehicleRef: 'veh-005',
            vehiclePlate: 'AG 3344 HI',
            driverRef: 'drv-003',
            driverName: 'Catur Wibowo',
            receiverName: 'Fajar Nugroho',
            receiverPhone: '081777100007',
            receiverAddress: 'Jl. Mastrip No. 77, Kediri',
            receiverCompany: 'Pusat Distribusi Kediri',
            pickupAddress: 'Gudang Gading Mas Surya - Tulangan',
            serviceRef: 'svc-003',
            serviceName: 'FTL',
            date: '2026-03-13',
            status: 'CANCELLED',
            notes: 'DO dibatalkan sebelum armada jalan.',
            trackingState: 'STOPPED',
            trackingStoppedAt: '2026-03-13T02:15:00Z',
        },
        {
            _id: 'do-008',
            _type: 'deliveryOrder',
            doNumber: 'DO-202603-0008',
            orderRef: 'order-009',
            masterResi: 'R-202603-0009',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            vehicleRef: 'veh-005',
            vehiclePlate: 'AG 3344 HI',
            driverRef: 'drv-003',
            driverName: 'Catur Wibowo',
            receiverName: 'Hendra Wijaya',
            receiverPhone: '081777100009',
            receiverAddress: 'Jl. Ahmad Dahlan No. 2, Kediri',
            receiverCompany: 'Baja Timur Kediri',
            pickupAddress: 'Pabrik Baja Timur - Gresik',
            serviceRef: 'svc-002',
            serviceName: 'Express',
            date: '2026-03-16',
            status: 'HEADING_TO_PICKUP',
            notes: 'Driver sedang menuju lokasi pickup.',
            trackingState: 'ACTIVE',
            trackingStartedAt: '2026-03-16T01:30:00Z',
            trackingLastSeenAt: '2026-03-16T08:57:00Z',
            trackingLastLat: -7.3982,
            trackingLastLng: 112.6451,
            trackingLastAccuracyM: 11,
            trackingLastSpeedKph: 36,
            trackingLastSource: 'DRIVER_APP',
        }
    );

    push(
        { _id: 'doi-001', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-001', orderItemRef: 'oi-001', orderItemDescription: 'Beras premium 25 kg', orderItemQtyKoli: 4, orderItemWeight: 80 },
        { _id: 'doi-002', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-001', orderItemRef: 'oi-002', orderItemDescription: 'Minyak goreng kemasan', orderItemQtyKoli: 6, orderItemWeight: 120 },
        { _id: 'doi-003', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-002', orderItemRef: 'oi-003', orderItemDescription: 'Plat baja ringan', orderItemQtyKoli: 8, orderItemWeight: 240 },
        { _id: 'doi-004', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-003', orderItemRef: 'oi-005', orderItemDescription: 'Resin batch A', orderItemQtyKoli: 5, orderItemWeight: 150 },
        { _id: 'doi-005', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-004', orderItemRef: 'oi-007', orderItemDescription: 'Bahan kemasan produksi', orderItemQtyKoli: 7, orderItemWeight: 210 },
        { _id: 'doi-006', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-005', orderItemRef: 'oi-009', orderItemDescription: 'Sparepart conveyor', orderItemQtyKoli: 3, orderItemWeight: 75 },
        { _id: 'doi-007', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-006', orderItemRef: 'oi-012', orderItemDescription: 'Biji plastik recycle', orderItemQtyKoli: 6, orderItemWeight: 180 },
        { _id: 'doi-008', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-007', orderItemRef: 'oi-011', orderItemDescription: 'Mesin packing', orderItemQtyKoli: 2, orderItemWeight: 180 },
        { _id: 'doi-009', _type: 'deliveryOrderItem', deliveryOrderRef: 'do-008', orderItemRef: 'oi-013', orderItemDescription: 'Plat potong custom', orderItemQtyKoli: 5, orderItemWeight: 140 },
    );

    push(
        { _id: 'tl-001', _type: 'trackingLog', refType: 'DO', refRef: 'do-001', status: 'CREATED', note: 'Surat jalan dibuat.', timestamp: '2026-03-03T00:45:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-002', _type: 'trackingLog', refType: 'DO', refRef: 'do-001', status: 'ON_DELIVERY', note: 'Armada berangkat dari gudang.', timestamp: '2026-03-03T01:20:00Z', userRef: 'user-driver-001', userName: 'Driver Agus', latitude: -7.4553, longitude: 112.7178, accuracyM: 8, speedKph: 35, source: 'DRIVER_APP' },
        { _id: 'tl-003', _type: 'trackingLog', refType: 'DO', refRef: 'do-001', status: 'DELIVERED', note: 'POD diterima customer.', timestamp: '2026-03-03T10:30:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-004', _type: 'trackingLog', refType: 'DO', refRef: 'do-002', status: 'CREATED', note: 'DO batch pertama dibuat.', timestamp: '2026-03-04T00:30:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-005', _type: 'trackingLog', refType: 'DO', refRef: 'do-002', status: 'DELIVERED', note: 'Batch pertama diterima pabrik.', timestamp: '2026-03-04T08:45:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-006', _type: 'trackingLog', refType: 'DO', refRef: 'do-003', status: 'CREATED', note: 'DO express dibuat.', timestamp: '2026-03-14T00:40:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-007', _type: 'trackingLog', refType: 'DO', refRef: 'do-003', status: 'HEADING_TO_PICKUP', note: 'Driver menuju lokasi pickup.', timestamp: '2026-03-14T01:00:00Z', userRef: 'user-driver-001', userName: 'Driver Agus', latitude: -7.2892, longitude: 112.7344, accuracyM: 7, speedKph: 28, source: 'DRIVER_APP' },
        { _id: 'tl-008', _type: 'trackingLog', refType: 'DO', refRef: 'do-003', status: 'ON_DELIVERY', note: 'Armada memasuki Tol Mojokerto.', timestamp: '2026-03-16T09:15:00Z', userRef: 'user-driver-001', userName: 'Driver Agus', latitude: -7.4721, longitude: 112.4412, accuracyM: 6, speedKph: 44, source: 'DRIVER_APP' },
        { _id: 'tl-009', _type: 'trackingLog', refType: 'DO', refRef: 'do-004', status: 'CREATED', note: 'DO Pasuruan dibuat.', timestamp: '2026-03-15T00:20:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-010', _type: 'trackingLog', refType: 'DO', refRef: 'do-004', status: 'ON_DELIVERY', note: 'Armada berangkat menuju Pasuruan.', timestamp: '2026-03-15T02:00:00Z', userRef: 'user-driver-002', userName: 'Driver Budi', latitude: -7.5335, longitude: 112.7075, accuracyM: 7, speedKph: 38, source: 'DRIVER_APP' },
        { _id: 'tl-011', _type: 'trackingLog', refType: 'DO', refRef: 'do-004', status: 'ARRIVED', note: 'Armada sudah tiba dan antre bongkar.', timestamp: '2026-03-16T08:10:00Z', userRef: 'user-driver-002', userName: 'Driver Budi', latitude: -7.6451, longitude: 112.9077, accuracyM: 10, speedKph: 0, source: 'DRIVER_APP' },
        { _id: 'tl-012', _type: 'trackingLog', refType: 'DO', refRef: 'do-005', status: 'CREATED', note: 'DO Jombang dibuat untuk jadwal besok.', timestamp: '2026-03-16T06:20:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-013', _type: 'trackingLog', refType: 'DO', refRef: 'do-006', status: 'CREATED', note: 'DO Kediri dibuat.', timestamp: '2026-03-05T00:25:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-014', _type: 'trackingLog', refType: 'DO', refRef: 'do-006', status: 'DELIVERED', note: 'POD Kediri selesai.', timestamp: '2026-03-05T08:30:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-015', _type: 'trackingLog', refType: 'DO', refRef: 'do-007', status: 'CREATED', note: 'DO FTL dibuat.', timestamp: '2026-03-13T01:20:00Z', userRef: 'user-owner-001', userName: 'Owner Utama', source: 'ADMIN_PANEL' },
        { _id: 'tl-016', _type: 'trackingLog', refType: 'DO', refRef: 'do-007', status: 'CANCELLED', note: 'DO dibatalkan oleh customer.', timestamp: '2026-03-13T02:15:00Z', userRef: 'user-owner-001', userName: 'Owner Utama', source: 'ADMIN_PANEL' },
        { _id: 'tl-017', _type: 'trackingLog', refType: 'DO', refRef: 'do-008', status: 'CREATED', note: 'DO Kediri cepat dibuat.', timestamp: '2026-03-16T00:45:00Z', userRef: 'user-admin-001', userName: 'Admin Operasional', source: 'ADMIN_PANEL' },
        { _id: 'tl-018', _type: 'trackingLog', refType: 'DO', refRef: 'do-008', status: 'HEADING_TO_PICKUP', note: 'Driver bergerak menuju pickup Gresik.', timestamp: '2026-03-16T01:30:00Z', userRef: 'user-driver-003', userName: 'Driver Catur', latitude: -7.3982, longitude: 112.6451, accuracyM: 9, speedKph: 33, source: 'DRIVER_APP' },
    );

    push(
        {
            _id: 'nota-001',
            _type: 'freightNota',
            notaNumber: 'NOTA-202603-0001',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            issueDate: '2026-03-04',
            dueDate: '2026-03-18',
            status: 'PARTIAL',
            totalAmount: 3_000_000,
            totalCollie: 10,
            totalWeightKg: 200,
            bankAccountRef: 'bank-jatim-001',
            notes: 'Termin pengiriman awal Maret untuk distribusi Sidoarjo.',
        },
        {
            _id: 'nota-002',
            _type: 'freightNota',
            notaNumber: 'NOTA-202603-0002',
            customerRef: 'cust-002',
            customerName: 'PT Baja Timur Abadi',
            issueDate: '2026-03-05',
            dueDate: '2026-04-04',
            status: 'PAID',
            totalAmount: 3_600_000,
            totalCollie: 8,
            totalWeightKg: 240,
            bankAccountRef: 'bank-jatim-001',
            notes: 'Tagihan batch baja ringan area Gresik.',
        },
        {
            _id: 'nota-003',
            _type: 'freightNota',
            notaNumber: 'NOTA-202603-0003',
            customerRef: 'cust-003',
            customerName: 'CV Sembada Plastik',
            issueDate: '2026-03-06',
            dueDate: '2026-03-27',
            status: 'UNPAID',
            totalAmount: 2_520_000,
            totalCollie: 6,
            totalWeightKg: 180,
            bankAccountRef: 'bank-jatim-001',
            notes: 'Nota belum jatuh tempo untuk pengiriman Kediri.',
        },
        {
            _id: 'notaitem-001',
            _type: 'freightNotaItem',
            notaRef: 'nota-001',
            doRef: 'do-001',
            doNumber: 'DO-202603-0001',
            vehiclePlate: 'W 8123 GS',
            date: '2026-03-03',
            noSJ: 'DO-202603-0001',
            dari: 'Gudang Gading Mas Surya - Tulangan',
            tujuan: 'Jl. Pelabuhan No. 5, Surabaya',
            barang: 'Beras premium 25 kg, Minyak goreng kemasan',
            collie: 10,
            beratKg: 200,
            tarip: 15_000,
            uangRp: 3_000_000,
            ket: 'Tagihan distribusi retail.',
        },
        {
            _id: 'notaitem-002',
            _type: 'freightNotaItem',
            notaRef: 'nota-002',
            doRef: 'do-002',
            doNumber: 'DO-202603-0002',
            vehiclePlate: 'L 9456 AB',
            date: '2026-03-04',
            noSJ: 'DO-202603-0002',
            dari: 'Pabrik Baja Timur - Gresik',
            tujuan: 'Jl. Kalianak Barat No. 11, Surabaya',
            barang: 'Plat baja ringan',
            collie: 8,
            beratKg: 240,
            tarip: 15_000,
            uangRp: 3_600_000,
            ket: 'Batch pertama baja ringan.',
        },
        {
            _id: 'notaitem-003',
            _type: 'freightNotaItem',
            notaRef: 'nota-003',
            doRef: 'do-006',
            doNumber: 'DO-202603-0006',
            vehiclePlate: 'AG 3344 HI',
            date: '2026-03-05',
            noSJ: 'DO-202603-0006',
            dari: 'Gudang Rungkut Industri II No. 7, Surabaya',
            tujuan: 'Jl. Veteran No. 5, Kediri',
            barang: 'Biji plastik recycle',
            collie: 6,
            beratKg: 180,
            tarip: 14_000,
            uangRp: 2_520_000,
            ket: 'Tagihan reguler Kediri.',
        }
    );

    push(
        {
            _id: 'pay-001',
            _type: 'payment',
            invoiceRef: 'nota-001',
            bankAccountRef: 'bank-jatim-001',
            bankAccountName: 'Bank Jatim',
            bankAccountNumber: '0201200300400',
            date: '2026-03-10',
            amount: 1_200_000,
            method: 'TRANSFER',
            note: 'Pembayaran termin pertama customer.',
        },
        {
            _id: 'pay-002',
            _type: 'payment',
            invoiceRef: 'nota-002',
            bankAccountRef: 'bank-cash-on-hand',
            bankAccountName: 'Kas Tunai',
            bankAccountNumber: 'CASH',
            date: '2026-03-05',
            amount: 3_600_000,
            method: 'CASH',
            note: 'Pelunasan tunai oleh customer di lokasi bongkar.',
        },
        {
            _id: 'inc-001',
            _type: 'income',
            sourceType: 'INVOICE_PAYMENT',
            paymentRef: 'pay-001',
            date: '2026-03-10',
            amount: 1_200_000,
            note: 'Pembayaran nota ongkos NOTA-202603-0001',
        },
        {
            _id: 'inc-002',
            _type: 'income',
            sourceType: 'INVOICE_PAYMENT',
            paymentRef: 'pay-002',
            date: '2026-03-05',
            amount: 3_600_000,
            note: 'Pembayaran nota ongkos NOTA-202603-0002',
        }
    );

    push(
        {
            _id: 'inv-001',
            _type: 'invoice',
            invoiceNumber: 'INV-202602-0001',
            mode: 'ORDER',
            customerRef: 'cust-001',
            customerName: 'PT Pangan Nusantara',
            masterResi: 'R-202602-0099',
            issueDate: '2026-02-28',
            dueDate: '2026-03-14',
            status: 'PAID',
            totalAmount: 1_750_000,
            notes: 'Invoice legacy sebelum migrasi ke Nota Ongkos.',
        },
        {
            _id: 'ii-001',
            _type: 'invoiceItem',
            invoiceRef: 'inv-001',
            description: 'Distribusi bahan sembako batch Februari',
            qty: 1,
            price: 1_000_000,
            subtotal: 1_000_000,
        },
        {
            _id: 'ii-002',
            _type: 'invoiceItem',
            invoiceRef: 'inv-001',
            description: 'Biaya handling dan bongkar muat',
            qty: 1,
            price: 750_000,
            subtotal: 750_000,
        },
        {
            _id: 'pay-003',
            _type: 'payment',
            invoiceRef: 'inv-001',
            bankAccountRef: 'bank-bca-001',
            bankAccountName: 'BCA',
            bankAccountNumber: '1234500012',
            date: '2026-03-06',
            amount: 1_750_000,
            method: 'TRANSFER',
            note: 'Pelunasan invoice legacy via transfer.',
        },
        {
            _id: 'inc-003',
            _type: 'income',
            sourceType: 'INVOICE_PAYMENT',
            paymentRef: 'pay-003',
            date: '2026-03-06',
            amount: 1_750_000,
            note: 'Pembayaran invoice legacy INV-202602-0001',
        }
    );

    push(
        {
            _id: 'bor-001',
            _type: 'driverBorongan',
            boronganNumber: 'BRG-202603-0001',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            periodStart: '2026-03-03',
            periodEnd: '2026-03-03',
            status: 'PAID',
            totalAmount: 1_350_000,
            totalCollie: 10,
            totalWeightKg: 200,
            notes: 'Borongan pengiriman retail Surabaya.',
            paidDate: '2026-03-07',
            paidMethod: 'TRANSFER',
            paidBankRef: 'bank-bca-001',
            paidBankName: 'BCA',
            paidBankNumber: '1234500012',
        },
        {
            _id: 'boritem-001',
            _type: 'driverBoronganItem',
            boronganRef: 'bor-001',
            doRef: 'do-001',
            doNumber: 'DO-202603-0001',
            vehiclePlate: 'W 8123 GS',
            date: '2026-03-03',
            noSJ: 'DO-202603-0001',
            tujuan: 'Jl. Pelabuhan No. 5, Surabaya',
            barang: 'Beras premium 25 kg, Minyak goreng kemasan',
            collie: 10,
            beratKg: 200,
            tarip: 1_350_000,
            uangRp: 1_350_000,
            ket: 'Borongan selesai dan sudah dibayar.',
        },
        {
            _id: 'bor-002',
            _type: 'driverBorongan',
            boronganNumber: 'BRG-202603-0002',
            driverRef: 'drv-002',
            driverName: 'Budi Hartono',
            periodStart: '2026-03-04',
            periodEnd: '2026-03-04',
            status: 'UNPAID',
            totalAmount: 672_000,
            totalCollie: 8,
            totalWeightKg: 240,
            notes: 'Borongan batch baja menunggu otorisasi owner.',
        },
        {
            _id: 'boritem-002',
            _type: 'driverBoronganItem',
            boronganRef: 'bor-002',
            doRef: 'do-002',
            doNumber: 'DO-202603-0002',
            vehiclePlate: 'L 9456 AB',
            date: '2026-03-04',
            noSJ: 'DO-202603-0002',
            tujuan: 'Jl. Kalianak Barat No. 11, Surabaya',
            barang: 'Plat baja ringan',
            collie: 8,
            beratKg: 240,
            tarip: 672_000,
            uangRp: 672_000,
            ket: 'Belum dibayarkan.',
        }
    );

    push(
        {
            _id: 'voucher-001',
            _type: 'driverVoucher',
            bonNumber: 'BON-202603-0001',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            deliveryOrderRef: 'do-001',
            doNumber: 'DO-202603-0001',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            route: 'Gudang Gading Mas Surya - Tulangan -> Jl. Pelabuhan No. 5, Surabaya',
            issuedDate: '2026-03-03',
            cashGiven: 900_000,
            issueBankRef: 'bank-bca-001',
            issueBankName: 'BCA',
            totalSpent: 700_000,
            balance: 200_000,
            status: 'SETTLED',
            notes: 'Bon operasional perjalanan retail Surabaya.',
            settledDate: '2026-03-04',
            settledBy: 'Admin Operasional',
            settlementBankRef: 'bank-bca-001',
            settlementBankName: 'BCA',
        },
        {
            _id: 'voucher-002',
            _type: 'driverVoucher',
            bonNumber: 'BON-202603-0002',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            deliveryOrderRef: 'do-003',
            doNumber: 'DO-202603-0003',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            route: 'Gudang Rungkut Industri II No. 7, Surabaya -> Jl. By Pass Mojokerto No. 12, Mojokerto',
            issuedDate: '2026-03-14',
            cashGiven: 450_000,
            issueBankRef: 'bank-cash-on-hand',
            issueBankName: 'Kas Tunai',
            totalSpent: 150_000,
            balance: 300_000,
            status: 'ISSUED',
            notes: 'Bon express untuk perjalanan aktif Mojokerto.',
        },
        {
            _id: 'vitem-001',
            _type: 'driverVoucherItem',
            voucherRef: 'voucher-001',
            category: 'BBM / Solar',
            description: 'Isi solar SPBU Waru',
            amount: 400_000,
        },
        {
            _id: 'vitem-002',
            _type: 'driverVoucherItem',
            voucherRef: 'voucher-001',
            category: 'Tol & Parkir',
            description: 'Tol Surabaya dan parkir bongkar',
            amount: 200_000,
        },
        {
            _id: 'vitem-003',
            _type: 'driverVoucherItem',
            voucherRef: 'voucher-001',
            category: 'Konsumsi Driver',
            description: 'Makan dan minum driver',
            amount: 100_000,
        },
        {
            _id: 'vitem-004',
            _type: 'driverVoucherItem',
            voucherRef: 'voucher-002',
            category: 'Tol & Parkir',
            description: 'Tiket tol Waru - Mojokerto',
            amount: 50_000,
        },
        {
            _id: 'vitem-005',
            _type: 'driverVoucherItem',
            voucherRef: 'voucher-002',
            category: 'Konsumsi Driver',
            description: 'Konsumsi saat antre loading',
            amount: 100_000,
        }
    );

    push(
        {
            _id: 'exp-001',
            _type: 'expense',
            categoryRef: 'expcat-004',
            categoryName: 'Operasional Kantor',
            date: '2026-03-08',
            amount: 1_500_000,
            note: 'Pembayaran internet kantor dan ATK bulanan.',
            description: 'Operasional kantor Maret',
            privacyLevel: 'internal',
            bankAccountRef: 'bank-jatim-001',
            bankAccountName: 'Bank Jatim',
            bankAccountNumber: '0201200300400',
        },
        {
            _id: 'mnt-001',
            _type: 'maintenance',
            vehicleRef: 'veh-002',
            vehiclePlate: 'L 9456 AB',
            type: 'Servis berkala dan ganti filter',
            scheduleType: 'DATE',
            plannedDate: '2026-03-10',
            status: 'DONE',
            completedDate: '2026-03-10',
            odometerAtService: 98_500,
            vendor: 'Bengkel Bina Armada',
            notes: 'Servis selesai tanpa temuan lanjutan.',
            relatedExpenseRef: 'exp-002',
            cost: 2_200_000,
        },
        {
            _id: 'exp-002',
            _type: 'expense',
            categoryRef: 'expcat-003',
            categoryName: 'Servis Kendaraan',
            date: '2026-03-10',
            amount: 2_200_000,
            note: 'Servis berkala L 9456 AB.',
            description: 'Maintenance kendaraan operasional Pasuruan',
            privacyLevel: 'internal',
            bankAccountRef: 'bank-bca-001',
            bankAccountName: 'BCA',
            bankAccountNumber: '1234500012',
            relatedVehicleRef: 'veh-002',
            relatedVehiclePlate: 'L 9456 AB',
            relatedMaintenanceRef: 'mnt-001',
        },
        {
            _id: 'exp-003',
            _type: 'expense',
            categoryRef: 'expcat-005',
            categoryName: 'Konsumsi Driver',
            date: '2026-03-15',
            amount: 350_000,
            note: 'Bekal trip armada Kediri.',
            description: 'Konsumsi driver dan helper',
            privacyLevel: 'internal',
            bankAccountRef: 'bank-cash-on-hand',
            bankAccountName: 'Kas Tunai',
            bankAccountNumber: 'CASH',
            relatedVehicleRef: 'veh-005',
            relatedVehiclePlate: 'AG 3344 HI',
        },
        {
            _id: 'exp-004',
            _type: 'expense',
            categoryRef: 'expcat-007',
            categoryName: 'Lain-lain',
            date: '2026-03-11',
            amount: 900_000,
            note: 'Biaya perizinan operasional.',
            description: 'Perpanjangan dokumen legal',
            privacyLevel: 'ownerOnly',
            bankAccountRef: 'bank-jatim-001',
            bankAccountName: 'Bank Jatim',
            bankAccountNumber: '0201200300400',
        },
        {
            _id: 'exp-bor-001',
            _type: 'expense',
            categoryRef: 'driver-borongan',
            categoryName: 'Borongan Supir',
            date: '2026-03-07',
            amount: 1_350_000,
            note: 'Pembayaran borongan Agus Santoso.',
            description: 'Upah borongan supir Agus Santoso - BRG-202603-0001',
            privacyLevel: 'internal',
            bankAccountRef: 'bank-bca-001',
            bankAccountName: 'BCA',
            bankAccountNumber: '1234500012',
            boronganRef: 'bor-001',
        },
        {
            _id: 'exp-vc-001',
            _type: 'expense',
            categoryRef: 'driver-voucher-bbm-solar',
            categoryName: 'BBM / Solar',
            date: '2026-03-04',
            amount: 400_000,
            note: 'Bon supir BON-202603-0001',
            description: 'Isi solar SPBU Waru',
            privacyLevel: 'internal',
            relatedVehicleRef: 'veh-001',
            relatedVehiclePlate: 'W 8123 GS',
            voucherRef: 'voucher-001',
        },
        {
            _id: 'exp-vc-002',
            _type: 'expense',
            categoryRef: 'driver-voucher-tol-parkir',
            categoryName: 'Tol & Parkir',
            date: '2026-03-04',
            amount: 200_000,
            note: 'Bon supir BON-202603-0001',
            description: 'Tol Surabaya dan parkir bongkar',
            privacyLevel: 'internal',
            relatedVehicleRef: 'veh-001',
            relatedVehiclePlate: 'W 8123 GS',
            voucherRef: 'voucher-001',
        },
        {
            _id: 'exp-vc-003',
            _type: 'expense',
            categoryRef: 'driver-voucher-konsumsi-driver',
            categoryName: 'Konsumsi Driver',
            date: '2026-03-04',
            amount: 100_000,
            note: 'Bon supir BON-202603-0001',
            description: 'Makan dan minum driver',
            privacyLevel: 'internal',
            relatedVehicleRef: 'veh-001',
            relatedVehiclePlate: 'W 8123 GS',
            voucherRef: 'voucher-001',
        },
        {
            _id: 'mnt-002',
            _type: 'maintenance',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            type: 'Ganti oli dan cek rem',
            scheduleType: 'DATE',
            plannedDate: '2026-03-20',
            status: 'SCHEDULED',
            notes: 'Jadwal servis sebelum trip luar kota berikutnya.',
        },
        {
            _id: 'mnt-003',
            _type: 'maintenance',
            vehicleRef: 'veh-003',
            vehiclePlate: 'N 7711 CD',
            type: 'Overhaul mesin',
            scheduleType: 'ODOMETER',
            plannedOdometer: 130_000,
            status: 'SKIPPED',
            notes: 'Unit sedang out of service menunggu keputusan owner.',
        },
        {
            _id: 'tire-001',
            _type: 'tireEvent',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            posisi: 'FRONT_LEFT',
            tireType: 'Tubeless',
            tireBrand: 'Bridgestone',
            tireSize: '225/75R16',
            installDate: '2025-12-01',
            notes: 'Ban depan kiri kondisi baik.',
        },
        {
            _id: 'tire-002',
            _type: 'tireEvent',
            vehicleRef: 'veh-002',
            vehiclePlate: 'L 9456 AB',
            posisi: 'REAR_RIGHT',
            tireType: 'Tubeless',
            tireBrand: 'GT Radial',
            tireSize: '225/75R16',
            installDate: '2025-10-10',
            replaceDate: '2026-03-10',
            notes: 'Diganti saat servis berkala.',
        },
        {
            _id: 'tire-003',
            _type: 'tireEvent',
            vehicleRef: 'veh-003',
            vehiclePlate: 'N 7711 CD',
            posisi: 'SPARE',
            tireType: 'Tube Type',
            tireBrand: 'Accelera',
            tireSize: '750R16',
            installDate: '2025-09-01',
            notes: 'Ban serep unit cadangan.',
        }
    );

    push(
        {
            _id: 'incident-001',
            _type: 'incident',
            incidentNumber: 'INC-202603-0001',
            dateTime: '2026-03-16T09:20:00Z',
            vehicleRef: 'veh-001',
            vehiclePlate: 'W 8123 GS',
            driverRef: 'drv-001',
            driverName: 'Agus Santoso',
            relatedDeliveryOrderRef: 'do-003',
            relatedDONumber: 'DO-202603-0003',
            incidentType: 'BLOWOUT_TIRE',
            urgency: 'HIGH',
            locationText: 'Tol Mojokerto KM 712',
            odometer: 120_450,
            description: 'Ban belakang kiri pecah saat menuju Mojokerto, armada berhenti di bahu jalan.',
            status: 'OPEN',
            assignedToUserRef: 'user-admin-001',
            assignedToUserName: 'Admin Operasional',
        },
        {
            _id: 'incident-002',
            _type: 'incident',
            incidentNumber: 'INC-202603-0002',
            dateTime: '2026-03-16T06:40:00Z',
            vehicleRef: 'veh-002',
            vehiclePlate: 'L 9456 AB',
            driverRef: 'drv-002',
            driverName: 'Budi Hartono',
            relatedDeliveryOrderRef: 'do-004',
            relatedDONumber: 'DO-202603-0004',
            incidentType: 'ENGINE_TROUBLE',
            urgency: 'MEDIUM',
            locationText: 'Area bongkar Pasuruan',
            odometer: 98_900,
            description: 'Indikator temperatur mesin naik saat menunggu bongkar.',
            status: 'IN_PROGRESS',
            assignedToUserRef: 'user-admin-001',
            assignedToUserName: 'Admin Operasional',
        },
        {
            _id: 'incident-003',
            _type: 'incident',
            incidentNumber: 'INC-202603-0003',
            dateTime: '2026-03-04T05:10:00Z',
            vehicleRef: 'veh-002',
            vehiclePlate: 'L 9456 AB',
            driverRef: 'drv-002',
            driverName: 'Budi Hartono',
            relatedDeliveryOrderRef: 'do-002',
            relatedDONumber: 'DO-202603-0002',
            incidentType: 'ACCIDENT_MINOR',
            urgency: 'LOW',
            locationText: 'Jl. Kalianak Barat, Surabaya',
            odometer: 98_120,
            description: 'Spion kanan tersenggol saat antre bongkar.',
            status: 'RESOLVED',
            assignedToUserRef: 'user-owner-001',
            assignedToUserName: 'Owner Utama',
        },
        {
            _id: 'incident-004',
            _type: 'incident',
            incidentNumber: 'INC-202603-0004',
            dateTime: '2026-03-09T02:15:00Z',
            vehicleRef: 'veh-003',
            vehiclePlate: 'N 7788 CD',
            driverRef: 'drv-004',
            driverName: 'Deni Prabowo',
            incidentType: 'OTHER',
            urgency: 'MEDIUM',
            locationText: 'Pool Tulangan',
            odometer: 129_800,
            description: 'Unit non-operasional dicatat mengalami kebocoran radiator.',
            status: 'CLOSED',
            assignedToUserRef: 'user-owner-001',
            assignedToUserName: 'Owner Utama',
        },
        {
            _id: 'ial-001',
            _type: 'incidentActionLog',
            incidentRef: 'incident-001',
            timestamp: '2026-03-16T09:25:00Z',
            note: 'Dispatcher menerima laporan dan meminta driver berhenti aman.',
            userRef: 'user-admin-001',
            userName: 'Admin Operasional',
        },
        {
            _id: 'ial-002',
            _type: 'incidentActionLog',
            incidentRef: 'incident-002',
            timestamp: '2026-03-16T06:55:00Z',
            note: 'Bengkel rekanan dihubungi untuk pengecekan kipas radiator.',
            userRef: 'user-admin-001',
            userName: 'Admin Operasional',
        },
        {
            _id: 'ial-003',
            _type: 'incidentActionLog',
            incidentRef: 'incident-002',
            timestamp: '2026-03-16T07:30:00Z',
            note: 'Mekanik onsite menuju lokasi bongkar Pasuruan.',
            userRef: 'user-owner-001',
            userName: 'Owner Utama',
        },
        {
            _id: 'ial-004',
            _type: 'incidentActionLog',
            incidentRef: 'incident-003',
            timestamp: '2026-03-04T07:10:00Z',
            note: 'Spion diganti dan unit dinyatakan lanjut operasi.',
            userRef: 'user-admin-001',
            userName: 'Admin Operasional',
        },
        {
            _id: 'ial-005',
            _type: 'incidentActionLog',
            incidentRef: 'incident-004',
            timestamp: '2026-03-09T05:45:00Z',
            note: 'Unit diparkirkan dan pekerjaan ditutup sambil menunggu keputusan perbaikan.',
            userRef: 'user-owner-001',
            userName: 'Owner Utama',
        }
    );

    push(
        {
            _id: 'audit-001',
            _type: 'auditLog',
            actorUserRef: 'user-owner-001',
            actorUserName: 'Owner Utama',
            action: 'LOGIN',
            entityType: 'session',
            entityRef: 'owner-session-20260316',
            changesSummary: 'Owner login ke dashboard utama.',
            timestamp: '2026-03-16T11:30:00Z',
        },
        {
            _id: 'audit-002',
            _type: 'auditLog',
            actorUserRef: 'user-admin-001',
            actorUserName: 'Admin Operasional',
            action: 'CREATE',
            entityType: 'delivery-orders',
            entityRef: 'do-008',
            changesSummary: 'Membuat surat jalan DO-202603-0008 untuk customer PT Baja Timur Abadi.',
            timestamp: '2026-03-16T00:45:00Z',
        },
        {
            _id: 'audit-003',
            _type: 'auditLog',
            actorUserRef: 'user-admin-001',
            actorUserName: 'Admin Operasional',
            action: 'CREATE',
            entityType: 'freight-notas',
            entityRef: 'nota-003',
            changesSummary: 'Membuat nota ongkos NOTA-202603-0003.',
            timestamp: '2026-03-06T08:15:00Z',
        },
        {
            _id: 'audit-004',
            _type: 'auditLog',
            actorUserRef: 'user-admin-001',
            actorUserName: 'Admin Operasional',
            action: 'CREATE',
            entityType: 'payments',
            entityRef: 'pay-001',
            changesSummary: 'Mencatat pembayaran termin pertama nota NOTA-202603-0001.',
            timestamp: '2026-03-10T09:05:00Z',
        },
        {
            _id: 'audit-005',
            _type: 'auditLog',
            actorUserRef: 'user-admin-001',
            actorUserName: 'Admin Operasional',
            action: 'CREATE',
            entityType: 'driver-borongans',
            entityRef: 'bor-001',
            changesSummary: 'Mencatat pembayaran borongan BRG-202603-0001.',
            timestamp: '2026-03-07T14:20:00Z',
        },
        {
            _id: 'audit-006',
            _type: 'auditLog',
            actorUserRef: 'user-admin-001',
            actorUserName: 'Admin Operasional',
            action: 'UPDATE',
            entityType: 'driver-vouchers',
            entityRef: 'voucher-001',
            changesSummary: 'Settlement bon supir BON-202603-0001.',
            timestamp: '2026-03-04T17:10:00Z',
        },
        {
            _id: 'audit-007',
            _type: 'auditLog',
            actorUserRef: 'user-owner-001',
            actorUserName: 'Owner Utama',
            action: 'UPDATE',
            entityType: 'incidents',
            entityRef: 'incident-003',
            changesSummary: 'Menandai insiden INC-202603-0003 sebagai resolved.',
            timestamp: '2026-03-04T07:15:00Z',
        },
        {
            _id: 'audit-008',
            _type: 'auditLog',
            actorUserRef: 'user-owner-001',
            actorUserName: 'Owner Utama',
            action: 'UPDATE',
            entityType: 'company',
            entityRef: 'company-001',
            changesSummary: 'Memperbarui branding dan nomor seri cetak nota.',
            timestamp: '2026-03-01T09:00:00Z',
        }
    );

    postBankTransaction({
        _id: 'btx-001',
        bankAccountRef: 'bank-jatim-001',
        type: 'TRANSFER_OUT',
        amount: 8_000_000,
        date: '2026-03-02',
        description: 'Transfer ke BCA untuk dana operasional',
        relatedTransferRef: 'trf-001',
    });
    postBankTransaction({
        _id: 'btx-002',
        bankAccountRef: 'bank-bca-001',
        type: 'TRANSFER_IN',
        amount: 8_000_000,
        date: '2026-03-02',
        description: 'Transfer dari Bank Jatim untuk dana operasional',
        relatedTransferRef: 'trf-001',
    });
    postBankTransaction({
        _id: 'btx-003',
        bankAccountRef: 'bank-jatim-001',
        type: 'DEBIT',
        amount: 1_500_000,
        date: '2026-03-08',
        description: 'Operasional kantor Maret',
        relatedExpenseRef: 'exp-001',
    });
    postBankTransaction({
        _id: 'btx-004',
        bankAccountRef: 'bank-bca-001',
        type: 'DEBIT',
        amount: 900_000,
        date: '2026-03-03',
        description: 'Pencairan bon supir BON-202603-0001',
        relatedVoucherRef: 'voucher-001',
    });
    postBankTransaction({
        _id: 'btx-005',
        bankAccountRef: 'bank-jatim-001',
        type: 'CREDIT',
        amount: 1_200_000,
        date: '2026-03-10',
        description: 'Pembayaran nota masuk',
        relatedPaymentRef: 'pay-001',
    });
    postBankTransaction({
        _id: 'btx-006',
        bankAccountRef: 'bank-bca-001',
        type: 'DEBIT',
        amount: 2_200_000,
        date: '2026-03-10',
        description: 'Maintenance kendaraan operasional Pasuruan',
        relatedExpenseRef: 'exp-002',
    });
    postBankTransaction({
        _id: 'btx-007',
        bankAccountRef: 'bank-bca-001',
        type: 'DEBIT',
        amount: 1_350_000,
        date: '2026-03-07',
        description: 'Pembayaran borongan BRG-202603-0001',
        relatedExpenseRef: 'exp-bor-001',
    });
    postBankTransaction({
        _id: 'btx-008',
        bankAccountRef: 'bank-bca-001',
        type: 'CREDIT',
        amount: 200_000,
        date: '2026-03-04',
        description: 'Pengembalian sisa bon BON-202603-0001',
        relatedVoucherRef: 'voucher-001',
    });
    postBankTransaction({
        _id: 'btx-009',
        bankAccountRef: 'bank-cash-on-hand',
        type: 'DEBIT',
        amount: 450_000,
        date: '2026-03-14',
        description: 'Pencairan bon supir BON-202603-0002',
        relatedVoucherRef: 'voucher-002',
    });
    postBankTransaction({
        _id: 'btx-010',
        bankAccountRef: 'bank-cash-on-hand',
        type: 'CREDIT',
        amount: 3_600_000,
        date: '2026-03-05',
        description: 'Pembayaran tunai masuk',
        relatedPaymentRef: 'pay-002',
    });
    postBankTransaction({
        _id: 'btx-011',
        bankAccountRef: 'bank-cash-on-hand',
        type: 'DEBIT',
        amount: 350_000,
        date: '2026-03-15',
        description: 'Konsumsi driver dan helper',
        relatedExpenseRef: 'exp-003',
    });
    postBankTransaction({
        _id: 'btx-012',
        bankAccountRef: 'bank-bca-001',
        type: 'CREDIT',
        amount: 1_750_000,
        date: '2026-03-06',
        description: 'Pembayaran invoice masuk',
        relatedPaymentRef: 'pay-003',
    });
    postBankTransaction({
        _id: 'btx-013',
        bankAccountRef: 'bank-jatim-001',
        type: 'DEBIT',
        amount: 900_000,
        date: '2026-03-11',
        description: 'Perpanjangan dokumen legal',
        relatedExpenseRef: 'exp-004',
    });

    push(...Object.values(bankAccounts));
}

async function seed() {
    buildSeedDocuments();
    console.log(`Seeding Sanity dataset: ${process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'}`);

    const batchSize = 50;
    for (let index = 0; index < documents.length; index += batchSize) {
        const batch = documents.slice(index, index + batchSize);
        let transaction = client.transaction();

        for (const doc of batch) {
            transaction = transaction.createOrReplace(doc);
        }

        await transaction.commit();
        console.log(`  Upserted ${Math.min(index + batch.length, documents.length)}/${documents.length}`);
    }

    console.log('Seed selesai.');
}

seed().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
